### ISSUE TITLE
nil pointer error when file contains receivers only 

### ISSUE THREAD

**Issue by davidhendi** [viant/toolbox#3]
when a file contains receivers and not the struct which the receivers point to, we get a nil pointer error: 

````
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
                panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xec95c]
 
goroutine 6 [running]:
panic(0x277480, 0xc420018090)
                /usr/local/go/src/runtime/panic.go:500 +0x1a1
testing.tRunner.func1(0xc420092180)
                /usr/local/go/src/testing/testing.go:579 +0x25d
panic(0x277480, 0xc420018090)
                /usr/local/go/src/runtime/panic.go:458 +0x243
github.com/viant/toolbox.(*StructInfo).AddReceivers(0x0, 0xc4204a8300, 0x1, 0x1)
                /Users/dhendi/workspaces/go_workspace/src/github.com/viant/toolbox/fileset_info.go:146 +0xfc
github.com/viant/toolbox.(*FileInfo).Visit(0xc4204c38b0, 0x1201860, 0xc42022ab70, 0x28f380, 0x1a)
                /Users/dhendi/workspaces/go_workspace/src/github.com/viant/toolbox/fileset_info.go:243 +0x28b
go/ast.Walk(0x3e9940, 0xc4204c38b0, 0x1201860, 0xc42022ab70)
                /usr/local/go/src/go/ast/walk.go:52 +0x63
go/ast.walkDeclList(0x3e9940, 0xc4204c38b0, 0xc420227b40, 0x4, 0x4)
                /usr/local/go/src/go/ast/walk.go:38 +0x89
go/ast.Walk(0x3e9940, 0xc4204c38b0, 0x3ec000, 0xc420220500)
                /usr/local/go/src/go/ast/walk.go:353 +0x29e4
github.com/viant/toolbox.NewFileSetInfo(0x2d709b, 0x57, 0x0, 0x0, 0x0)
                /Users/dhendi/workspaces/go_workspace/src/github.com/viant/toolbox/fileset_info.go:312 +0x399 
````

**Comment by adranwit** [comment]
Issued has been addressed, and unit test has been added
