### ISSUE TITLE
TestNewHttpStorageService fails at go test

### ISSUE THREAD

**Issue by rogers0** [viant/toolbox#35]
error log for version 0.32.2:
```
=== RUN   TestNewHttpStorageService
    TestNewHttpStorageService: http_service_test.go:20:
                Error Trace:    http_service_test.go:20
                Error:          Should be true
                Test:           TestNewHttpStorageService
--- FAIL: TestNewHttpStorageService (0.02s)
panic: runtime error: index out of range [0] with length 0 [recovered]
        panic: runtime error: index out of range [0] with length 0

goroutine 22 [running]:
testing.tRunner.func1.1(0x84f5c0, 0xc0000d4c00)
        /usr/lib/go-1.14/src/testing/testing.go:940 +0x2f5
testing.tRunner.func1(0xc0000d7320)
        /usr/lib/go-1.14/src/testing/testing.go:943 +0x3f9
panic(0x84f5c0, 0xc0000d4c00)
        /usr/lib/go-1.14/src/runtime/panic.go:969 +0x166  
github.com/viant/toolbox/storage_test.TestNewHttpStorageService(0xc0000d7320)
        /build/golang-github-viant-toolbox-0.32.2/obj-x86_64-linux-gnu/src/github.com/viant/toolbox/storage/http_service_test.go:21 +0x377
testing.tRunner(0xc0000d7320, 0x89f108)
        /usr/lib/go-1.14/src/testing/testing.go:991 +0xdc 
created by testing.(*T).Run
        /usr/lib/go-1.14/src/testing/testing.go:1042 +0x357
FAIL    github.com/viant/toolbox/storage        0.082s
```

**Comment by adranwit** [comment]
updated test

**Comment by rogers0** [comment]
Confirmed it's fixed. Thank you!
